name: Delete workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'


jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete_workflow_runs
        uses: smallprogram/delete-workflow-runs@main
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
