# File: .github/workflows/repo-sync.yml
name: merge-from-oxo
on:
  schedule:
    - cron: '30 */2 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ mian ]
  repository_dispatch:
    types: sync-lxk0301-jd_scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # 我自己同步到gitee使用，其他人可忽略
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false


      - name: Merge main from master
        uses: devmasx/merge-branch@v1.3.1
        if: env.PAT
        with:
          type: now
          from_branch: oxo
          target_branch: ooo
          github_token: ${{ secrets.PAT }}
