name: sync-dust

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */2 * * *'
  repository_dispatch:
    types: sync-dust

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y && apt-get install -y build-essential git git-core curl wget && apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

    - name: Clone Master
      run: |
        git clone -b dust git@share.r2ray.com:dust dust
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        directory: dust
        github_token: ${{ secrets.PAT }}
        branch: dust
        repository: "kddhi/akd"
